services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  SchulIT\CommonBundle\Controller\CronjobController:
    tags:
      - 'controller.service_arguments'

  SchulIT\CommonBundle\Command\PruneCronjobResultsCommand:
    tags:
      - { name: 'shapecode_cron.cron_job', expression: '@daily' }
