services:
  SchulIT\CommonBundle\Controller\CronjobController:
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - 'controller.service_arguments'

  SchulIT\CommonBundle\Commands\PruneCronjobResultsCommand:
    tags:
      - { name: shapecode_cron.cron_job, expression: '@daily' }
